version: "3.9"

services:
  streamlit:
    build: ./streamlit_app
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    networks:
      - rag-net

  locust:
    build: ./locust
    container_name: locust_ui
    ports:
      - "8089:8089"
    networks:
      - rag-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - rag-net

  backend:
    image: python:3.11-slim
    container_name: rag_backend
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge

